version: '2.4'
services:
  traefik:
    image: stefanscherer/traefik-windows
    command: --docker.endpoint=npipe:////./pipe/docker_engine --logLevel=DEBUG
    ports:
      - "8080:8080"
      - "443:443"
    volumes:
      - .:C:/etc/traefik
#      - C:/Users/vagrant/.docker:C:/etc/ssl
      - type: npipe
        source: \\.\pipe\docker_engine
        target: \\.\pipe\docker_engine

  whoami1:
    image: stefanscherer/whoami-windows
    labels:
      - "traefik.backend=whoami"
      - "traefik.frontend.entryPoints=https"
      - "traefik.frontend.rule=Host:whoami.yourdomain.com"

  whoami2:
    image: stefanscherer/whoami-windows
    labels:
      - "traefik.backend=whoami"
      - "traefik.frontend.entryPoints=https"
      - "traefik.frontend.rule=Host:whoami.yourdomain.com"

#  portainer:
#    image: portainer/portainer
#    labels:
#      - "traefik.backend=portainer"
#      - "traefik.frontend.rule=Host:portainer.yourdomain.com"

networks:
  default:
    external:
      name: nat
