version: "2.1"

services:
  web:
    build: .
    command: nodemon --debug=5858
    volumes:
      - .:c:\code
    ports:
      - "8000:8000"
      - "5858:5858"

networks:
  default:
    external:
      name: nat
